name = "thoughtcatcher-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[[d1_databases]]
binding = "DB"
database_name = "thoughtcatcher-db"
database_id = "c2a82d6b-cc52-45e1-a725-fc0603e15841"

[vars]
JWT_SECRET = "thoughtcatcher-jwt-secret-2026-make-this-long-and-random"

[observability]
enabled = true
